TEMP_DIR_NAME = "temp_data"
PROJECT_ID = 'sp-ed-advana-dev-2j72' #(dev, ambiente mínimo donde quedaría si lo automatizamos)
COLUMNS_ACTIVATE = ['target', 'updateDateTime', 'countryCode', 'origin',
                    'destination', 'flightNumber', 'departureTime',
                    'Migrated', 'directSale', 'stationId', 
                    'documentTypes', 'duration', 'cabinClass', 'bookingClass', 'fareBasis', 'equipment',
                    'origin_ndc', 'origin_detail_ndc',
                    'ssr_all_marks',  'has_registered_incident',
                    'flight_marks',
                    'tour_code',  'Dummy_GSTN', 'Dummy_CRPE', 'Dummy_INFR', 'Dummy_DEPU',
                    'Dummy_MEDA', 'Dummy_AUTK', 'Dummy_SMSR', 'Dummy_LAXP',
                    'Dummy_BRND', 'Dummy_WCHC', 'Dummy_WCMP', 'Dummy_OTH',
                    'Dummy_XBAF', 'Dummy_SETA', 'Dummy_INFT', 'Dummy_INAD',
                    'Dummy_SPEQ', 'Dummy_LOKX', 'Dummy_LCML', 'Dummy_TWOV',
                    'Dummy_NOCM', 'Dummy_WCHS', 'Dummy_GSSV', 'Dummy_GRPS',
                    'Dummy_PCDA', 'Dummy_TKNE', 'Dummy_DEPA', 'Dummy_RFIC',
                    'Dummy_TLAC', 'Dummy_FOID', 'Dummy_CHML', 'Dummy_XBGS',
                    'Dummy_SUCF', 'Dummy_CKIN', 'Dummy_CRPP', 'Dummy_KSML',
                    'Dummy_VIPD', 'Dummy_SSAS', 'Dummy_ADTK', 'Dummy_MENU',
                    'Dummy_DOCA', 'Dummy_SVAN', 'Dummy_GBAG', 'Dummy_GSSC',
                    'Dummy_OXYG', 'Dummy_VOML', 'Dummy_DCVI', 'Dummy_GSTA',
                    'Dummy_NSSW', 'reissuing_type', 'plating_airline', 'pax_type',
                    'status_coupon','operating_booking_class',
                    'FB_class_mkt', 'tour_code', 'flag_rt', 'aaa_city_code',
                    'home_city_code', 'oac_acc_code', 'agent_sine', 'gds_code',
                    'prorate_type', 'fare_calculation_type', 'flag_dcp', 'branded_fare',
                    'issuing_type', 'codeshare_involved','nego_group_flag', 'flag_group', 'flag_private'] # 'codeshare_involved', 

DUMMY_TARGET_VARIABLES = ['target','Dummy_GSTN', 'Dummy_CRPE', 'Dummy_INFR', 'Dummy_DEPU',
                           'Dummy_MEDA', 'Dummy_AUTK', 'Dummy_SMSR', 'Dummy_LAXP',
                           'Dummy_BRND', 'Dummy_WCHC', 'Dummy_WCMP', 'Dummy_OTH',
                           'Dummy_XBAF', 'Dummy_SETA', 'Dummy_INFT', 'Dummy_INAD',
                           'Dummy_SPEQ', 'Dummy_LOKX', 'Dummy_LCML', 'Dummy_TWOV',
                           'Dummy_NOCM', 'Dummy_WCHS', 'Dummy_GSSV', 'Dummy_GRPS',
                           'Dummy_PCDA', 'Dummy_TKNE', 'Dummy_DEPA', 'Dummy_RFIC',
                           'Dummy_TLAC', 'Dummy_FOID', 'Dummy_CHML', 'Dummy_XBGS',
                           'Dummy_SUCF', 'Dummy_CKIN', 'Dummy_CRPP', 'Dummy_KSML',
                           'Dummy_VIPD', 'Dummy_SSAS', 'Dummy_ADTK', 'Dummy_MENU',
                           'Dummy_DOCA', 'Dummy_SVAN', 'Dummy_GBAG', 'Dummy_GSSC',
                           'Dummy_OXYG', 'Dummy_VOML', 'Dummy_DCVI', 'Dummy_GSTA',
                           'Dummy_NSSW', 'codeshare_involved','FB_class_mkt']#], 'codeshare_involved'

ENCODERS_VARIABLES = ['countryCode', 'origin', 'destination', 'flightNumber', 
                      'Migrated', 'directSale', 'stationId', 
                      'documentTypes', 'cabinClass', 'bookingClass', 
                      'fareBasis', 'equipment','origin_ndc', 
                      'has_registered_incident', 'flight_marks', 'reissuing_type', 'plating_airline', 'pax_type',
                      'status_coupon', 'operating_booking_class',
                      'flag_rt', 'aaa_city_code', 'home_city_code', 'oac_acc_code', 
                      'agent_sine', 'gds_code', 'prorate_type', 
                      'flag_dcp', 'branded_fare', 'issuing_type', 'nego_group_flag', 
                      'flag_group', 'flag_private']

CONTINUOS_VARIABLE = ['fare_calculation_type', 'duration']
CONFIG_RF = {"class_weight":"balanced",
                         "criterion":"entropy",
                         "random_state":2342,
                         "n_estimators":20}